# Generated by Django 3.0.8 on 2020-07-16 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Box description')),
                ('in_session', models.BooleanField(default=False, verbose_name='Box currently in session?')),
                ('box_type', models.IntegerField(verbose_name='0: Everyday, 1: Tue/Thu, 2: Fri')),
                ('last_used', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front_text', models.CharField(max_length=150, verbose_name='Front text')),
                ('back_text', models.TextField(verbose_name='Back text')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last modified on')),
                ('on_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='leitner.Box')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150, verbose_name='Deck description')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cards_on_box', models.IntegerField(verbose_name='Total cards of the current box')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Is the session finished?')),
                ('current_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='leitner.Box')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='leitner.Deck')),
            ],
        ),
        migrations.CreateModel(
            name='SessionFinishedCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_session', to='leitner.Card')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finished_cards', to='leitner.Session')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='on_deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='leitner.Deck'),
        ),
        migrations.AddField(
            model_name='box',
            name='deck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='leitner.Deck'),
        ),
    ]
