# Generated by Django 3.0.7 on 2020-07-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flash',
            name='content',
            field=models.TextField(verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='flash',
            name='last_change_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified on'),
        ),
        migrations.AlterField(
            model_name='flash',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
    ]
