# Generated by Django 3.0.7 on 2020-07-02 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20200702_1341'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flash',
            old_name='last_change_date',
            new_name='updated_at',
        ),
    ]
