# Generated by Django 3.0.8 on 2020-07-07 22:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0003_auto_20200702_1341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flash',
            new_name='Note',
        ),
    ]
